export const ROUTES = {
  HOME: '/',
  EVENTS: '/events',
  EVENT_CATEGORY: (category: string) => `/events/${category}`,
  PRODUCT: (id: string) => `/product/${id}`,
  GALLERY: '/gallery',
  CONTACT: '/contact',
  ABOUT: '/about',
  TERMS: '/terms',
  PRIVACY: '/privacy',
  REFUND_POLICY: '/refund-policy',
  CANCELLATION_POLICY: '/cancellation-policy',
  ADMIN: {
    DASHBOARD: '/admin',
    ORDERS: '/admin/orders',
    PRODUCTS: '/admin/products',
    CATEGORIES: '/admin/categories',
    GALLERY: '/admin/gallery',
    COUPONS: '/admin/coupons',
    REVIEWS: '/admin/reviews',
  },
  AUTH: {
    LOGIN: '/auth/login',
    SIGNUP: '/auth/signup',
  },
  PROFILE: '/profile',
  PROFILE_ORDERS: '/profile/orders',
  PROFILE_WISHLIST: '/profile/wishlist',
  PROFILE_ADDRESSES: '/profile/addresses',
  PROFILE_NOTIFICATIONS: '/profile/notifications',
  CART: '/cart',
  CHECKOUT: '/checkout',
  CHECKOUT_SUCCESS: '/checkout/success',
  SEARCH: '/search',
} as const